repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: detect-private-key


  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        pass_filenames: true
        files: ^(app/|tests/|scripts/)
        args: [--check]

      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        pass_filenames: true
        files: ^(app/|tests/|scripts/)
        args: [--check-only, --profile, black]

      - id: ruff
        name: ruff
        entry: poetry run ruff
        language: system
        types: [python]
        pass_filenames: true
        files: ^(app/|tests/|scripts/)
        args: [check]

      - id: bandit
        name: bandit
        entry: poetry run bandit
        language: system
        types: [python]
        args: ["-c", "pyproject.toml"]

      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        require_serial: true
        pass_filenames: false
        args: [app, tests]
